### ISSUE TITLE
Remove logging, replace with console.log

### ISSUE THREAD

**Issue by jgrund** [intel-hpdd/srcmap-reverse#32]
Remove dedicated logging and replace with console.log.

Once we bundle as a systemd service it will just write to journalctl.

**Comment by johnsonw** [comment]
Do we want to replace all logging with console.log? I was thinking it might make sense to replace log.error with `console.error`?

**Comment by jgrund** [comment]
That works

**Comment by johnsonw** [comment]
The messages display when running the test now. While not incorrect, are we ok with this? 
![image](https://user-images.githubusercontent.com/1100657/27977371-6bf726a6-6338-11e7-91ce-a6be3979cc71.png)

**Comment by jgrund** [comment]
Jest has a silent flag: http://facebook.github.io/jest/docs/en/cli.html#silent. When doing these changes, use the supervisor-status repo as a reference: https://github.com/intel-hpdd/supervisor-status/blob/master/package.json#L8
